### ISSUE TITLE
Errors when running with the defaults 

### ISSUE THREAD

**Issue by challs1** [nccgroup/aws-inventory#11]
I am using ec2 Linux server having  Python 2.7.14 a version for this 
Traceback (most recent call last):
  File "aws_inventory.py", line 320, in <module>
    main(parse_args())
  File "aws_inventory.py", line 317, in main
    aws_inventory.invoker.ApiInvoker(args, service_descriptors, ops_count).start()
  File "/home/ec2-user/aws-inventory/aws_inventory/invoker.py", line 44, in start
    self._probe_services)
  File "/home/ec2-user/aws-inventory/aws_inventory/progress.py", line 16, in __init__
    ttk.Frame.__init__(self, relief='ridge', borderwidth=2)
  File "/usr/lib64/python2.7/lib-tk/ttk.py", line 738, in __init__
    Widget.__init__(self, master, "ttk::frame", kw)
  File "/usr/lib64/python2.7/lib-tk/ttk.py", line 551, in __init__
    master = setup_master(master)
  File "/usr/lib64/python2.7/lib-tk/ttk.py", line 354, in setup_master
    master = Tkinter._default_root or Tkinter.Tk()
  File "/usr/lib64/python2.7/lib-tk/Tkinter.py", line 1819, in __init__
    self.tk = _tkinter.create(screenName, baseName, className, interactive, wantobjects, useTk, sync, use)
_tkinter.TclError: no display name and no $DISPLAY environment variable

**Comment by bitsandsalsa** [comment]
see #8
