### ISSUE TITLE
UnicodeDecodeError: 'utf8' codec can't decode byte 0x82 in position 1: invalid start byte

### ISSUE THREAD

**Issue by pedroj84** [nccgroup/aws-inventory#19]
When you run the script with the following parameters
python aws_inventory.py --profile my-profile-name --region my-region --debug -v

It breaks up at the end with the following error without writing json file:

DEBUG:aws_inventory.store:Building the response store.
Exception in thread Thread-1:
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 801, in __bootstrap_inner
    self.run()
  File "/usr/lib/python2.7/threading.py", line 754, in run
    self.__target(*self.__args, **self.__kwargs)
  File "/home/pedroj84/aws-inventory/aws_inventory/invoker.py", line 99, in _probe_services
    self.write_results()
  File "/home/pedroj84/aws-inventory/aws_inventory/invoker.py", line 124, in write_results
    print self.store.get_response_store()
  File "/home/pedroj84/aws-inventory/aws_inventory/store.py", line 83, in get_response_store
    return json.dumps(self._response_store, cls=ResponseEncoder)
  File "/usr/lib/python2.7/json/__init__.py", line 251, in dumps
    sort_keys=sort_keys, **kw).encode(obj)
  File "/usr/lib/python2.7/json/encoder.py", line 207, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "/usr/lib/python2.7/json/encoder.py", line 270, in iterencode
    return _iterencode(o, 0)
UnicodeDecodeError: 'utf8' codec can't decode byte 0x82 in position 1: invalid start byte

**Comment by ncc-erik-steringer** [comment]
Cleaning out issues. I can't figure out, based on the details given, where the issue exactly is. Were you able to pin this down more? If so, could you share what you found?

**Comment by jjpestacio** [comment]
@ncc-erik-steringer I encountered the same issue. After some investigation, I learned that AWS will send some responses with non-ASCII characters. Both the response and exception stores are pickled into bytes. JSON cannot load the stores after unpickling because the strings contain non-ASCII characters.

To fix, all values in the response and exception stores must be utf-8 encoded before pickling (or encoded after pickling and before JSON loading).

**Comment by ncc-erik-steringer** [comment]
@jjpestacio , do you happen to know which responses from AWS do this? Also, have you seen if the `develop` branch has the same behavior (Python 3 only): https://github.com/nccgroup/aws-inventory/tree/develop

**Comment by jjpestacio** [comment]
I'm not sure which exact responses contain non-ASCII characters, but they were mostly related to languages e.g. "Sign-up using Español." I haven't verified if the problem persists in the Python3 version but I think it will - regardless of Python2 or Python3 we're using the same botocore version so the responses will be the same.

**Comment by jjpestacio** [comment]
Also fwiw, here's the workaround I'm doing:

`aws_inventory/store.py`
```
@@ -88,7 +87,8 @@ class ResultStore(object):
         :param file fp: file to write to
         """
         LOGGER.debug('Writing the response store to file "%s".', fp.name)
-        pickle.dump(self._response_store, fp)
+        encoded_store = {k: str(v).encode("utf-8") for k, v in self._response_store.items()}
+        pickle.dump(encoded_store, fp)

@@ -96,13 +96,15 @@ class ResultStore(object):
         :param file fp: file to write to
         """
         LOGGER.debug('Writing the exception store to file "%s".', fp.name)
-        pickle.dump(self._exception_store, fp)
+        encoded_store = {k: str(v).encode("utf-8") for k, v in self._exception_store.items()}
+        pickle.dump(encoded_store, fp)
```
