### ISSUE TITLE
output file with no desktop

### ISSUE THREAD

**Issue by shumyster** [nccgroup/aws-inventory#21]
Running EC2 instance of ubuntu 18.04, no desktop.

Even though I installed the python-tk (sudo apt-get install python-tk), I get the following stacktrace which has been mentioned in other issue reports: 

Traceback (most recent call last):
  File "aws_inventory.py", line 320, in <module>
    main(parse_args())
  File "aws_inventory.py", line 317, in main
    aws_inventory.invoker.ApiInvoker(args, service_descriptors, ops_count).start()
  File "/home/ubuntu/aws-inventory/aws_inventory/invoker.py", line 44, in start
    self._probe_services)
  File "/home/ubuntu/aws-inventory/aws_inventory/progress.py", line 16, in __init__
    ttk.Frame.__init__(self, relief='ridge', borderwidth=2)
  File "/usr/lib/python2.7/lib-tk/ttk.py", line 738, in __init__
    Widget.__init__(self, master, "ttk::frame", kw)
  File "/usr/lib/python2.7/lib-tk/ttk.py", line 551, in __init__
    master = setup_master(master)
  File "/usr/lib/python2.7/lib-tk/ttk.py", line 354, in setup_master
    master = Tkinter._default_root or Tkinter.Tk()
  File "/usr/lib/python2.7/lib-tk/Tkinter.py", line 1822, in __init__
    self.tk = _tkinter.create(screenName, baseName, className, interactive, wantobjects, useTk, sync, use)
_tkinter.TclError: no display name and no $DISPLAY environment variable

>>  running the python -m command also showed the same output

sudo python -m Tkinter
Traceback (most recent call last):
  File "/usr/lib/python2.7/runpy.py", line 174, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/usr/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/usr/lib/python2.7/lib-tk/Tkinter.py", line 3864, in <module>
    _test()
  File "/usr/lib/python2.7/lib-tk/Tkinter.py", line 3839, in _test
    root = Tk()
  File "/usr/lib/python2.7/lib-tk/Tkinter.py", line 1822, in __init__
    self.tk = _tkinter.create(screenName, baseName, className, interactive, wantobjects, useTk, sync, use)
_tkinter.TclError: no display name and no $DISPLAY environment variable

What I am looking for is the output file of the scan. I can offload the ~/aws-inventory/gui directory to my Win desktop, get the gui working, but looking for the data file to upload.
not sure if the scan produced an output file due to the error above, but if it has, please provide output location.

Thanks.

**Comment by dariushazimi** [comment]
Same issue here, can't find the output file

**Comment by AdallomRoy** [comment]
If you're using Ubuntu or any other *nix distro, you can use xvfb to create a virtual screen, that will make it finish.
Something like this:
`
apt-get install -y xvfb
xvfb-run python aws_inventory.py
`

**Comment by ncc-erik-steringer** [comment]
Cleaning out issues. Would you be able to try the `develop` branch, which shifted to Python 3 support, to see if that works better?

**Comment by mengmann** [comment]
Tested with python3 and develop branch with docker. I got my inventory.json file inside the gui folder
