### ISSUE TITLE
Issue with Dependency

### ISSUE THREAD

**Issue by deveddev** [nccgroup/aws-inventory#25]
I have installed the requests dependency via pip but the program is not locating it.

After running: python aws_inventory.py

this error is received

Traceback (most recent call last):
  File "aws_inventory.py", line 11, in <module>
    import aws_inventory.invoker
  File "/Users/edwarddevitt/Desktop/aws-inventory-master/aws_inventory/invoker.py", line 8, in <module>
    from opinel.utils.credentials import read_creds
  File "/Library/Python/2.7/site-packages/opinel/utils/credentials.py", line 11, in <module>
    import requests # TODO: get rid of that and make sure urllib2 validates certs ?
ImportError: No module named requests

The strange part is that I have already installed requests.

**Comment by bitsandsalsa** [comment]
How did you install the requirements for this tool? The recommended way as shown in the README is `pip install -r requirements.txt`. That should install all dependencies.

You can quickly test if the `requests` package is installed with something like: `python -c import requests`. If there is no exception, then it is installed.

**Comment by ncc-erik-steringer** [comment]
Hi there. Did the suggestion from @bitsandsalsa resolve this issue? Please let me know.
