### ISSUE TITLE
Connection timeout & no data-file

### ISSUE THREAD

**Issue by Michael-Fritsch** [nccgroup/aws-inventory#26]
Hi, 

running inventory seems successful on UI, but it creates no data-file:

```
ConnectTimeoutError: Connect timeout on endpoint URL: "https://ec2.eu-central-1.amazonaws.com/"
ERROR:aws_inventory.invoker:Unknown error while invoking API for service "ec2" in region "eu-central-1".
Traceback (most recent call last):
  File "D:\applications\aws-inventory-master\aws_inventory\invoker.py", line 163, in svc_worker
    response = getattr(params['client'], py_op)()
  File "C:\Users\michael.fritsch\.windows-build-tools\python27\lib\site-packages\botocore\client.py", line 357, in _api_call
    return self._make_api_call(operation_name, kwargs)
  File "C:\Users\michael.fritsch\.windows-build-tools\python27\lib\site-packages\botocore\client.py", line 648, in _make_api_call
    operation_model, request_dict, request_context)
  File "C:\Users\michael.fritsch\.windows-build-tools\python27\lib\site-packages\botocore\client.py", line 667, in _make_request
    return self._endpoint.make_request(operation_model, request_dict)
  File "C:\Users\michael.fritsch\.windows-build-tools\python27\lib\site-packages\botocore\endpoint.py", line 102, in make_request
    return self._send_request(request_dict, operation_model)
  File "C:\Users\michael.fritsch\.windows-build-tools\python27\lib\site-packages\botocore\endpoint.py", line 137, in _send_request
    success_response, exception):
  File "C:\Users\michael.fritsch\.windows-build-tools\python27\lib\site-packages\botocore\endpoint.py", line 231, in _needs_retry
    caught_exception=caught_exception, request_dict=request_dict)
  File "C:\Users\michael.fritsch\.windows-build-tools\python27\lib\site-packages\botocore\hooks.py", line 356, in emit
    return self._emitter.emit(aliased_event_name, **kwargs)
  File "C:\Users\michael.fritsch\.windows-build-tools\python27\lib\site-packages\botocore\hooks.py", line 228, in emit
    return self._emit(event_name, kwargs)
  File "C:\Users\michael.fritsch\.windows-build-tools\python27\lib\site-packages\botocore\hooks.py", line 211, in _emit
    response = handler(**kwargs)
  File "C:\Users\michael.fritsch\.windows-build-tools\python27\lib\site-packages\botocore\retryhandler.py", line 183, in __call__
    if self._checker(attempts, response, caught_exception):
  File "C:\Users\michael.fritsch\.windows-build-tools\python27\lib\site-packages\botocore\retryhandler.py", line 251, in __call__
    caught_exception)
  File "C:\Users\michael.fritsch\.windows-build-tools\python27\lib\site-packages\botocore\retryhandler.py", line 277, in _should_retry
    return self._checker(attempt_number, response, caught_exception)
  File "C:\Users\michael.fritsch\.windows-build-tools\python27\lib\site-packages\botocore\retryhandler.py", line 317, in __call__
    caught_exception)
  File "C:\Users\michael.fritsch\.windows-build-tools\python27\lib\site-packages\botocore\retryhandler.py", line 223, in __call__
    attempt_number, caught_exception)
  File "C:\Users\michael.fritsch\.windows-build-tools\python27\lib\site-packages\botocore\retryhandler.py", line 359, in _check_caught_exception
    raise caught_exception
ConnectTimeoutError: Connect timeout on endpoint URL: "https://ec2.eu-central-1.amazonaws.com/"
DEBUG:aws_inventory.store:Building the GUI data model.
Exception in thread Thread-1:
Traceback (most recent call last):
  File "C:\Users\michael.fritsch\.windows-build-tools\python27\lib\threading.py", line 801, in __bootstrap_inner
    self.run()
  File "C:\Users\michael.fritsch\.windows-build-tools\python27\lib\threading.py", line 754, in run
    self.__target(*self.__args, **self.__kwargs)
  File "D:\applications\aws-inventory-master\aws_inventory\invoker.py", line 99, in _probe_services
    self.write_results()
  File "D:\applications\aws-inventory-master\aws_inventory\invoker.py", line 130, in write_results
    self.store.generate_data_file(out_fp)
  File "D:\applications\aws-inventory-master\aws_inventory\store.py", line 148, in generate_data_file
    for service in data[0]['children']:
KeyError: 'children'
```

Is there any solution?

regards,
Michael

**Comment by bitsandsalsa** [comment]
Given your report, it's hard to say what the issue is. My guess is you had a very narrow filter set on the commandline that reduced the amount of resources to inspect. All requests made by the tool to inspect those resources failed leaving no actual response data to show in the GUI tool. It doesn't look like the tool handles that error case.

**Comment by ncc-erik-steringer** [comment]
Hi there. Did the feedback from @bitsandsalsa  help resolve this issue?
