### ISSUE TITLE
ImportError: No module named config

### ISSUE THREAD

**Issue by chilithomas** [nccgroup/aws-inventory#4]
**Traceback (most recent call last):
  File "aws_inventory.py", line 9, in <module>
    import aws_inventory.config
  File "/Users/john_white/aws-inventory-master/aws_inventory.py", line 9, in <module>
    import aws_inventory.config
ImportError: No module named config**

**Comment by chilithomas** [comment]
I was missing a folder ... re-cloned aws-inventory and the error is gone now. Back to work.

**Comment by chilithomas** [comment]
virtualenv
