### ISSUE TITLE
TKinter  TCL Error  no display name and no $DISPLAY environment variable

### ISSUE THREAD

**Issue by chilithomas** [nccgroup/aws-inventory#5]
**Traceback (most recent call last):
  File "aws_inventory.py", line 334, in <module>
    main(parse_args())
  File "aws_inventory.py", line 331, in main
    aws_inventory.invoker.ApiInvoker(args, service_descriptors, ops_count).start()
  File "/home/john_white/aws-inventory/aws_inventory/invoker.py", line 44, in start
    self._probe_services)
  File "/home/john_white/aws-inventory/aws_inventory/progress.py", line 16, in __init__
    ttk.Frame.__init__(self, relief='ridge', borderwidth=2)
  File "/usr/lib/python2.7/lib-tk/ttk.py", line 738, in __init__
    Widget.__init__(self, master, "ttk::frame", kw)
  File "/usr/lib/python2.7/lib-tk/ttk.py", line 551, in __init__
    master = setup_master(master)
  File "/usr/lib/python2.7/lib-tk/ttk.py", line 354, in setup_master
    master = Tkinter._default_root or Tkinter.Tk()
  File "/usr/lib/python2.7/lib-tk/Tkinter.py", line 1818, in __init__
    self.tk = _tkinter.create(screenName, baseName, className, interactive, wantobjects, useTk, sync, use)
_tkinter.TclError: no display name and no $DISPLAY environment variable**

**Comment by chilithomas** [comment]
_tkinter.TclError: couldn't connect to display "Cheese"

**Comment by chilithomas** [comment]
Figured that for me it only works on Ubuntu Desktop (specifically using 18 but that's alright). apt install python-tk is the only setup I had to do for display. btw looks like some great aws inventory code thanks ncc group.

**Comment by challs1** [comment]
@chilithomas : I am using ubuntu 18 but still i am facing the same issue u posted here. Can u help me to figure it out  and get rid of those please?

Traceback (most recent call last):
  File "aws_inventory.py", line 320, in <module>
    main(parse_args())
  File "aws_inventory.py", line 317, in main
    aws_inventory.invoker.ApiInvoker(args, service_descriptors, ops_count).start()
  File "/home/ubuntu/aws-inventory/aws_inventory/invoker.py", line 44, in start
    self._probe_services)
  File "/home/ubuntu/aws-inventory/aws_inventory/progress.py", line 16, in __init__
    ttk.Frame.__init__(self, relief='ridge', borderwidth=2)
  File "/usr/lib/python2.7/lib-tk/ttk.py", line 738, in __init__
    Widget.__init__(self, master, "ttk::frame", kw)
  File "/usr/lib/python2.7/lib-tk/ttk.py", line 551, in __init__
    master = setup_master(master)
  File "/usr/lib/python2.7/lib-tk/ttk.py", line 354, in setup_master
    master = Tkinter._default_root or Tkinter.Tk()
  File "/usr/lib/python2.7/lib-tk/Tkinter.py", line 1822, in __init__
    self.tk = _tkinter.create(screenName, baseName, className, interactive, wantobjects, useTk, sync, use)
_tkinter.TclError: no display name and no $DISPLAY environment variable

**Comment by shumyster** [comment]
Using Ubuntu 18 without desktop, just looking to offload the gui directory unde the aws-inventory to my Win desktop (AWS Inventory/gui/dist/index.html). I can get the browser showing, but can't find the json data file to import into it.

after running the scan I did get the error in question: 

Traceback (most recent call last):
  File "aws_inventory.py", line 320, in <module>
    main(parse_args())
  File "aws_inventory.py", line 317, in main
    aws_inventory.invoker.ApiInvoker(args, service_descriptors, ops_count).start()
  File "/home/ubuntu/aws-inventory/aws_inventory/invoker.py", line 44, in start
    self._probe_services)
  File "/home/ubuntu/aws-inventory/aws_inventory/progress.py", line 16, in __init__
    ttk.Frame.__init__(self, relief='ridge', borderwidth=2)
  File "/usr/lib/python2.7/lib-tk/ttk.py", line 738, in __init__
    Widget.__init__(self, master, "ttk::frame", kw)
  File "/usr/lib/python2.7/lib-tk/ttk.py", line 551, in __init__
    master = setup_master(master)
  File "/usr/lib/python2.7/lib-tk/ttk.py", line 354, in setup_master
    master = Tkinter._default_root or Tkinter.Tk()
  File "/usr/lib/python2.7/lib-tk/Tkinter.py", line 1822, in __init__
    self.tk = _tkinter.create(screenName, baseName, className, interactive, wantobjects, useTk, sync, use)
_tkinter.TclError: no display name and no $DISPLAY environment variable

help would be appreciated, cheers.
