### ISSUE TITLE
Profile was not running And the issue was this can u help me out?

### ISSUE THREAD

**Issue by sairaja992** [nccgroup/aws-inventory#8]
Traceback (most recent call last):
  File "aws_inventory.py", line 11, in <module>
    import aws_inventory.invoker
  File "/home/ec2-user/saipoc/aws-inventory/aws_inventory/invoker.py", line 11, in <module>
    import progress
  File "/home/ec2-user/saipoc/aws-inventory/aws_inventory/progress.py", line 5, in <module>
    import Tkinter as tk
ImportError: No module named Tkinter

**Comment by challs1** [comment]
@bitsandsalsa  I am using the linux and i have done those but still i am facing the issue.

**Comment by bitsandsalsa** [comment]
The title of this GitHub issue does not speak to the Python stack trace above. I am assuming the problem has to do with the Python stack trace.

I see you have a home directory of *ec2-user*. That is indicative of an AWS instance which does not by default have GUI functionality.

What distribution of Linux? If Tk is properly installed, the following file should exist: */usr/lib/python2.7/lib-dynload/_tkinter.so*. Does it exist? There is a Tk demo you can run to see if it is working and the version: `python -m Tkinter`. What version of Python are you using: `python -V`?

**Comment by challs1** [comment]
@bitsandsalsa : I am using the ubuntu 18 server . I am facing the following issues. If u have some time can u help me to figure it out? It will help me a lot. Thanks.

Traceback (most recent call last):
  File "aws_inventory.py", line 320, in <module>
    main(parse_args())
  File "aws_inventory.py", line 317, in main
    aws_inventory.invoker.ApiInvoker(args, service_descriptors, ops_count).start()
  File "/home/ubuntu/aws-inventory/aws_inventory/invoker.py", line 44, in start
    self._probe_services)
  File "/home/ubuntu/aws-inventory/aws_inventory/progress.py", line 16, in __init__
    ttk.Frame.__init__(self, relief='ridge', borderwidth=2)
  File "/usr/lib/python2.7/lib-tk/ttk.py", line 738, in __init__
    Widget.__init__(self, master, "ttk::frame", kw)
  File "/usr/lib/python2.7/lib-tk/ttk.py", line 551, in __init__
    master = setup_master(master)
  File "/usr/lib/python2.7/lib-tk/ttk.py", line 354, in setup_master
    master = Tkinter._default_root or Tkinter.Tk()
  File "/usr/lib/python2.7/lib-tk/Tkinter.py", line 1822, in __init__
    self.tk = _tkinter.create(screenName, baseName, className, interactive, wantobjects, useTk, sync, use)
_tkinter.TclError: no display name and no $DISPLAY environment variable
