### ISSUE TITLE
Getting error in ubuntu

### ISSUE THREAD

**Issue by challs1** [nccgroup/aws-inventory#9]
I have installed in ubuntu server and added all the dependiences that was required but still iam facing the issue. Can u help me to sort it out????

Traceback (most recent call last):
  File "aws_inventory.py", line 320, in <module>
    main(parse_args())
  File "aws_inventory.py", line 317, in main
    aws_inventory.invoker.ApiInvoker(args, service_descriptors, ops_count).start()
  File "/home/ubuntu/saipoc/aws-inventory/aws_inventory/invoker.py", line 44, in start
    self._probe_services)
  File "/home/ubuntu/saipoc/aws-inventory/aws_inventory/progress.py", line 16, in __init__
    ttk.Frame.__init__(self, relief='ridge', borderwidth=2)
  File "/usr/lib/python2.7/lib-tk/ttk.py", line 738, in __init__
    Widget.__init__(self, master, "ttk::frame", kw)
  File "/usr/lib/python2.7/lib-tk/ttk.py", line 551, in __init__
    master = setup_master(master)
  File "/usr/lib/python2.7/lib-tk/ttk.py", line 354, in setup_master
    master = Tkinter._default_root or Tkinter.Tk()
  File "/usr/lib/python2.7/lib-tk/Tkinter.py", line 1818, in __init__
    self.tk = _tkinter.create(screenName, baseName, className, interactive, wantobjects, useTk, sync, use)
_tkinter.TclError: no display name and no $DISPLAY environment variable

**Comment by bitsandsalsa** [comment]
The tool has a GUI component. I think your issue is that your Ubuntu server is not set up for GUI apps. If you are remotely connecting to your server over SSH, you can try to use the X forwarding feature. It is enabled with the `-X` commandline option to `ssh`.
